# Generated by Django 4.2.6 on 2023-11-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindetails',
            name='age',
        ),
        migrations.RemoveField(
            model_name='admindetails',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='admindetails',
            name='number',
        ),
        migrations.AddField(
            model_name='admindetails',
            name='password',
            field=models.CharField(default='20231128130314', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admindetails',
            name='username',
            field=models.CharField(default='admin_20231128130225', max_length=150),
        ),
    ]
