# Generated by Django 4.2.6 on 2023-11-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInfo', '0002_remove_admindetails_age_remove_admindetails_cnic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='username',
            field=models.CharField(default='admin_20231128130913', max_length=150),
        ),
    ]
