# Generated by Django 4.2.7 on 2023-12-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminInfo', '0004_alter_admindetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='username',
            field=models.CharField(default='admin_20231201201851', max_length=150),
        ),
    ]
