# Generated by Django 4.2.6 on 2023-11-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientInfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='patient_details',
            field=models.ForeignKey(default='20231128130456', on_delete=django.db.models.deletion.CASCADE, to='patientInfo.patientdetails'),
            preserve_default=False,
        ),
    ]
